### ISSUE TITLE
增加隐藏状态栏功能

### ISSUE THREAD

**Issue by amokiel** [asadahimeka/pixiv-viewer-apk#2]
移动端体验很不错，状态栏有点不太沉浸，有白边。可以考虑增加隐藏状态栏功能，这样就可以解决这个问题了。推荐的壁纸都挺不错的，平时自己的账户总是推荐那几种类型的，在这里让我浏览到很多之前没关注的内容，也是一种良好的体验。多谢开发者，辛苦了！

**Comment by asadahimeka** [comment]
这个是 webview 套壳打包的 [pixiv-viewer](https://pixiv.pics) 网站，网站也支持 PWA 安装；
状态栏等我研究看看，在我手机上没啥问题（

**Comment by asadahimeka** [comment]
可以用 [一个木函](https://www.coolapk.com/apk/com.One.WoodenLetter) 里的 `网页转应用` 功能
